import React, { useContext } from "react";
import { assets, plans } from "../assets/assets";
import { AppContext } from "../Context/AppContext";
import { motion } from "motion/react";
import { useNavigate } from "react-router-dom";
import { toast } from "react-toastify";
import axios from "axios";
const BuyCredit = () => {
  const { user, backendUrl, loadCreditsData, token, setShowLogin } =
    useContext(AppContext);
  const navigate = useNavigate();

  const initPay = async (order) => {
    const options = {
      key: import.meta.env.VITE_RAZORPAY_KEY_ID,
      amount: order.amount, // amount in smallest currency unit
      currency: order.currency,
      name: "Credits Payment",
      description: "Credits Payment",
      order_id: order.id, // Replace with the order ID generated by your server
      receipt: order.receipt,
      handler: async (response) => {
        try {
          const { data } = await axios.post(
            `${backendUrl}/api/user/verify-razor`,
            response,
            {
              headers: {
                Authorization: `Bearer ${token}`,
              },
            }
          );
          if(data.success){
            loadCreditsData()
            navigate('/')
            toast.success("Credit Added Successfully");
          }
        } catch (error) {
          toast.error(error.message);
        }
      },
    };
    const razorpay = new window.Razorpay(options);
    razorpay.open();
  };
  const paymentRazorpay = async (planId) => {
    try {
      if (!user) {
        setShowLogin(true);
        return;
      }
      const { data } = await axios.post(
        `${backendUrl}/api/user/pay-razor`,
        {
          userId: user.id,
          planId,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      if (data.success) {
        initPay(data.order);
        toast.success("Payment successful");
      }
    } catch (error) {
      toast.error(error.message);
      console.error("Payment failed", error);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0.2, y: 100 }}
      transition={{ duration: 1 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      className="min-h-[80vh] text-center pt-14 mb-10"
    >
      <button className="border border-gray-400 px-10 py-2 rounded-full mb-6">
        Our Plans
      </button>
      <h1 className="text-center text-3xl font-medium mb-6 sm:mb-10">
        Choose the Plan
      </h1>
      <div className="flex flex-wrap justify-center gap-6 text-left ">
        {plans.map((plan, index) => (
          <div
            key={index}
            className="bg-white drop-sahdow-sm border rounded-lg py-12 px-8
             text-gray-600 hover:scale-105 transition-all duration-500"
          >
            <img src={assets.logo_icon} alt="" width={40} />
            <p className="mt-3 mb-1 font-semibold">{plan.id}</p>
            <p className="text-sm">{plan.desc}</p>
            <p className="mt-6">
              <span className="text-3xl font-medium">${plan.price} </span>/{" "}
              {plan.credits} credits
            </p>
            <button
              onClick={() => paymentRazorpay(plan.id)}
              className="w-full bg-gray-800 text-white mt-8 text-sm
             rounded-md py-2.5 min-w-52"
            >
              {user ? "Buy Now" : "Get Started"}
            </button>
          </div>
        ))}
      </div>
    </motion.div>
  );
};

export default BuyCredit;
